version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ml-platform
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - ml-platform
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - ml-platform
    entrypoint: >
      /bin/sh -c "
      until mc alias set myminio http://minio:9000 minioadmin minioadmin; do
        echo 'Waiting for MinIO...';
        sleep 2;
      done;

      mc mb myminio/datasets --ignore-existing;
      mc mb myminio/ml-models --ignore-existing;

      exit 0;
      "

  user-service:
    image: hamshith/user-service:latest
    ports:
      - "8000:8000"
    env_file:
      - "./services/user-service/.env"
    networks:
      - ml-platform

  training-orchestrator:
    image: hamshith/training-orchestrator:latest
    env_file:
      - "./services/training-orchestrator/.env"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - ml-platform

  recommendation-service:
    image: hamshith/recommendation-service:latest
    ports:
      - "8002:8002"
    env_file:
      - "./services/recommendation-service/.env"
    networks:
      - ml-platform

  preprocessing-service:
    image: hamshith/preprocessing-service:latest
    env_file:
      - "./services/preprocessing-service/.env"
    depends_on:
      minio-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy  
    networks:
      - ml-platform

  model-registry-service:
    image: hamshith/model-registry-service:latest
    ports:
      - "8003:8003"
    env_file:
      - "./services/model-registery-service/.env"
    depends_on:
      minio-init:
        condition: service_completed_successfully
    networks:
      - ml-platform

  medium-model-training-service:
    image: hamshith/medium-model-training-service:latest
    env_file:
      - "./services/medium-model-training-service/.env"
    depends_on:
      minio-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    networks:
      - ml-platform

  low-model-training-service:
    image: hamshith/low-model-training-service:latest
    env_file:
      - "./services/low-model-training-service/.env"
    depends_on:
      minio-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    networks:
      - ml-platform

  high-model-training-service:
    image: hamshith/high-model-training-service:latest
    env_file:
      - "./services/high-model-training-service/.env"
    depends_on:
      minio-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    networks:
      - ml-platform

  dataset-service:
    image: hamshith/dataset-service:latest
    ports:
      - "8001:8001"
    env_file:
      - "./services/dataset-service/.env"
    depends_on:
      minio-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    networks:
      - ml-platform

  credit-service:
    image: hamshith/credit-service:latest
    ports:
      - "8004:8004"
    env_file:
      - "./services/credit-service/.env"
    networks:
      - ml-platform

  frontend:
    image: hamshith/frontend:latest
    ports:
      - "5173:5173"
    env_file:
      - "./frontend/.env"
    depends_on:
      - user-service
      - dataset-service
      - recommendation-service
      - model-registry-service
      - credit-service
    networks:
      - ml-platform

volumes:
  rabbitmq_data:
  minio_data:

networks:
  ml-platform:
    driver: bridge